FROM node:12

#Set a work directory inside the application
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY ../ServiceDiscovery/package*.json ./

RUN npm install

# Bundle app source
COPY ../ServiceDiscovery/. .

CMD [ "node", "ServiceDiscovery.js" ]